version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: weibeld/ubuntu-networking
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo ${DASTI}
            cat /etc/issue
            ls -ltrh $VAR_TEST
            # sudo apt-get update
            # sudo apt-get install -y iputils-ping
            # ping $WP_URL